---
swagger: '2.0'
info:
  title: Dev Analytics Affiliation API
  version: '1.0'
  description: Dev Analytics Affiliations API
basePath: /v1
paths:
  /health:
    get:
      summary: Health
      operationId: getHealth
      produces:
        - application/json
      responses:
        "200":
          description: "Success"
          headers:
            X-REQUEST-ID:
              type: string
              description: Request ID
          schema:
            $ref: "#/definitions/health"
        "400":
          $ref: "#/responses/invalid-request"
        "401":
          $ref: "#/responses/unauthorized"
        "403":
          $ref: "#/responses/forbidden"
      tags:
        - health
  /affiliation/{orgName}/add_domain/{domain}/to_project/{projectSlug}:
    put:
      summary: Add domain to organization (if not exists) and affiliate all profiles with that domain to this organization
      operationId: putOrgDomain
      produces:
        - application/json
      responses:
        "200":
          description: "Successfully added domain to organization"
          headers:
            X-REQUEST-ID:
              type: string
              description: Request ID
          schema:
            $ref: "#/definitions/put-org-domain-output"
        "400":
          $ref: "#/responses/invalid-request"
        "401":
          $ref: "#/responses/unauthorized"
        "404":
          $ref: "#/responses/not-found"
        "500":
          $ref: "#/responses/internal-server-error"
      tags:
        - affiliation
        - organization
        - domain
      parameters:
        - name: orgName
          in: path
          type: string
          required: true
          description: Organization name to add domain to (URL encoded)
        - name: domain
          in: path
          type: string
          required: true
          description: Domain to be added
        - name: projectSlug
          in: path
          type: string
          required: true
          description: Project slug URL encoded like 'academy-software-foundation/opencue'
        - name: overwrite
          in: query
          type: boolean
          default: false
          description: If set, it will overwrite existing affiliations for users with matching domains
        - name: is_top_domain
          in: query
          type: boolean
          default: false
          description: If set, it will set top domain flag to true
        - name: Authorization
          in: header
          type: string
          required: true
  /affiliation/{projectSlug}/merge_profiles/{fromUUID}/{toUUID}:
    put:
      summary: Merge Profiles fromUUID into toUUID
      operationId: putMergeProfiles
      produces:
        - application/json
      responses:
        "200":
          description: "Successfully merged profiles"
          headers:
            X-REQUEST-ID:
              type: string
              description: Request ID
          schema:
            $ref: "#/definitions/profile-data-output"
        "400":
          $ref: "#/responses/invalid-request"
        "401":
          $ref: "#/responses/unauthorized"
        "404":
          $ref: "#/responses/not-found"
        "500":
          $ref: "#/responses/internal-server-error"
      tags:
        - affiliation
        - merge
      parameters:
        - name: fromUUID
          in: path
          type: string
          required: true
          description: Profile UUID to merge from
        - name: toUUID
          in: path
          type: string
          required: true
          description: Profile UUID to merge to
        - name: projectSlug
          in: path
          type: string
          required: true
          description: Project slug URL encoded like 'academy-software-foundation/opencue'
        - name: Authorization
          in: header
          type: string
          required: true
  /affiliation/{projectSlug}/move_identity/{fromID}/{toUUID}:
    put:
      summary: Move identity from fromID to profile toUUID
      operationId: putMoveIdentity
      produces:
        - application/json
      responses:
        "200":
          description: "Successfully moved identity"
          headers:
            X-REQUEST-ID:
              type: string
              description: Request ID
          schema:
            $ref: "#/definitions/profile-data-output"
        "400":
          $ref: "#/responses/invalid-request"
        "401":
          $ref: "#/responses/unauthorized"
        "404":
          $ref: "#/responses/not-found"
        "500":
          $ref: "#/responses/internal-server-error"
      tags:
        - affiliation
        - merge
      parameters:
        - name: fromID
          in: path
          type: string
          required: true
          description: Identity ID to merge from
        - name: toUUID
          in: path
          type: string
          required: true
          description: Profile UUID to merge to
        - name: projectSlug
          in: path
          type: string
          required: true
          description: Project slug URL encoded like 'academy-software-foundation/opencue'
        - name: Authorization
          in: header
          type: string
          required: true
definitions:
  health:
    type: object
    title: Health
    description: Properties for Health
    properties:
      DateTime:
        type: string
        example: "2019-05-29 16:55:53.849593192 +0900 KST m=+12.237337959"
      DevAnalyticsAffiliationService:
        type: string
        example: "Running"
  error-response:
    type: object
    title: Error Response
    description: Standard error format
    properties:
      Code:
        type: string
      Message:
        type: string
  put-org-domain-output:
    title: Put Org Domain Output
    description: Stats and info about adding domain to organization
    type: object
    properties:
      deleted:
        type: string
        example: 12
      added:
        type: string
        example: 8
      info:
        type: string
        example: no such organization Mikrosoft
      user:
        type: string
        example: lukaszgryglicki
      scope:
        type: string
        example: academy-software-foundation/opencue
  profile-data-output:
    title: Profile data output
    description: Profile data
    type: object
    properties:
      uuid:
        type: string
        example: 00024380e0d8d854b42bf505333f245de77bd71d
      name:
        type: string
        x-nullable: true
        example: lukaszgryglicki
      email:
        type: string
        x-nullable: true
        example: lgryglicki@cncf.io
      gender:
        type: string
        example: male
        x-nullable: true
      gender_acc:
        type: integer
        example: 100
        x-nullable: true
      is_bot:
        type: integer
        # database doesn't have null, but we can use to to call Editprofile and skip updating is_bot
        x-nullable: true  
        example: 1
      country_code:
        type: string
        x-nullable: true
        example: PL
  country-data-output:
    title: Country data output
    description: Country data
    type: object
    properties:
      code:
        type: string
        example: PL
      name:
        type: string
        example: Poland
      alpha3:
        type: string
        example: POL
  identity-data-output:
    title: Identity data output
    description: Identity data
    type: object
    properties:
      id:
        type: string
        example: 16fe424acecf8d614d102fc0ece919a22200481d
      uuid:
        type: string
        example: 00024380e0d8d854b42bf505333f245de77bd71d
      source:
        type: string
        example: github
      name:
        type: string
        x-nullable: true
        example: Lukasz Gryglicki
      username:
        type: string
        x-nullable: true
        example: lukaszgryglicki
      email:
        type: string
        x-nullable: true
        example: lgryglicki@cncf.io
      last_modified:
        type: string
        format: date-time
        x-nullable: true
        example: '2019-09-02 03:00:33.000000'
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
responses:
  unauthorized:
    description: Unauthorized
    schema:
      $ref: "#/definitions/error-response"
  invalid-request:
    description: Invalid request
    schema:
      $ref: "#/definitions/error-response"
  forbidden:
    description: Insufficient privilege to execute action.
    schema:
      $ref: "#/definitions/error-response"
  not-found:
    description: Not found.
    schema:
      $ref: "#/definitions/error-response"
  conflict:
    description: Duplicate resource
    schema:
      $ref: "#/definitions/error-response"
  internal-server-error:
    description: Internal server error
    schema:
      $ref: "#/definitions/error-response"
