{{- $skipSecrets := .Values.skipSecrets -}}
{{ if not $skipSecrets }}
{{- $apiDBEndpoint := .Files.Get (printf "secrets/API_DB_ENDPOINT.%s.secret" .Values.deployEnv) -}}
{{- $shDBEndpoint := .Files.Get (printf "secrets/SH_DB_ENDPOINT.%s.secret" .Values.deployEnv) -}}
{{- $shDBROEndpoint := .Files.Get (printf "secrets/SH_DB_RO_ENDPOINT.%s.secret" .Values.deployEnv) -}}
{{- $esURL := .Files.Get (printf "secrets/ELASTIC_URL.%s.secret" .Values.deployEnv) -}}
{{- $esUser := .Files.Get (printf "secrets/ELASTIC_USERNAME.%s.secret" .Values.deployEnv) -}}
{{- $esPass := .Files.Get (printf "secrets/ELASTIC_PASSWORD.%s.secret" .Values.deployEnv) -}}
{{- $auth0Cid := .Files.Get (printf "secrets/AUTH0_CLIENT_ID.%s.secret" .Values.deployEnv) -}}
{{- $auth0Dom := .Files.Get (printf "secrets/AUTH0_DOMAIN.%s.secret" .Values.deployEnv) -}}
{{- $auth0Ucl := .Files.Get (printf "secrets/AUTH0_USERNAME_CLAIM.%s.secret" .Values.deployEnv) -}}
{{- $cors := .Files.Get (printf "secrets/CORS_ALLOWED_ORIGINS.%s.secret" .Values.deployEnv) -}}
{{- $syncUrl := .Files.Get (printf "secrets/SYNC_URL.%s.secret" .Values.deployEnv) -}}
{{- $esCacheURL := .Files.Get (printf "secrets/ELASTIC_CACHE_URL.%s.secret" .Values.deployEnv) -}}
{{- $esCacheUser := .Files.Get (printf "secrets/ELASTIC_CACHE_USERNAME.%s.secret" .Values.deployEnv) -}}
{{- $esCachePass := .Files.Get (printf "secrets/ELASTIC_CACHE_PASSWORD.%s.secret" .Values.deployEnv) -}}
{{- $esLogURL := .Files.Get (printf "secrets/ELASTIC_LOG_URL.%s.secret" .Values.deployEnv) -}}
{{- $esLogUser := .Files.Get (printf "secrets/ELASTIC_LOG_USERNAME.%s.secret" .Values.deployEnv) -}}
{{- $esLogPass := .Files.Get (printf "secrets/ELASTIC_LOG_PASSWORD.%s.secret" .Values.deployEnv) -}}
{{- $stage := .Files.Get (printf "secrets/STAGE.%s.secret" .Values.deployEnv) -}}
{{- $auth0Gt := .Files.Get (printf "secrets/AUTH0_GRANT_TYPE.%s.secret" .Values.deployEnv) -}}
{{- $auth0Cs := .Files.Get (printf "secrets/AUTH0_CLIENT_SECRET.%s.secret" .Values.deployEnv) -}}
{{- $auth0Aud := .Files.Get (printf "secrets/AUTH0_AUDIENCE.%s.secret" .Values.deployEnv) -}}
{{- $auth0TokenURL := .Files.Get (printf "secrets/AUTH0_TOKEN_ENDPOINT.%s.secret" .Values.deployEnv) -}}
{{- $platformOrgURL := .Files.Get (printf "secrets/PLATFORM_ORG_SERVICE_ENDPOINT.%s.secret" .Values.deployEnv) -}}
{{- $slackWebhookURL := .Files.Get (printf "secrets/SLACK_WEBHOOK_URL.%s.secret" .Values.deployEnv) -}}
---
apiVersion: v1
data:
  API_DB_ENDPOINT.secret: {{ $apiDBEndpoint | b64enc }}
  SH_DB_ENDPOINT.secret: {{ $shDBEndpoint | b64enc }}
  SH_DB_RO_ENDPOINT.secret: {{ $shDBROEndpoint | b64enc }}
  ELASTIC_URL.secret: {{ $esURL | b64enc }}
  ELASTIC_USERNAME.secret: {{ $esUser | b64enc }}
  ELASTIC_PASSWORD.secret: {{ $esPass | b64enc }}
  AUTH0_CLIENT_ID.secret: {{ $auth0Cid | b64enc }}
  AUTH0_DOMAIN.secret: {{ $auth0Dom | b64enc }}
  AUTH0_USERNAME_CLAIM.secret: {{ $auth0Ucl | b64enc }}
  CORS_ALLOWED_ORIGINS.secret: {{ $cors | b64enc }}
  SYNC_URL.secret: {{ $syncUrl | b64enc }}
  ELASTIC_CACHE_URL.secret: {{ $esCacheURL | b64enc }}
  ELASTIC_CACHE_USERNAME.secret: {{ $esCacheUser | b64enc }}
  ELASTIC_CACHE_PASSWORD.secret: {{ $esCachePass | b64enc }}
  ELASTIC_LOG_URL.secret: {{ $esLogURL | b64enc }}
  ELASTIC_LOG_USERNAME.secret: {{ $esLogUser | b64enc }}
  ELASTIC_LOG_PASSWORD.secret: {{ $esLogPass | b64enc }}
  STAGE.secret: {{ $stage | b64enc }}
  AUTH0_GRANT_TYPE.secret: {{ $auth0Gt | b64enc }}
  AUTH0_CLIENT_SECRET.secret: {{ $auth0Cs | b64enc }}
  AUTH0_AUDIENCE.secret: {{ $auth0Aud | b64enc }}
  AUTH0_TOKEN_ENDPOINT.secret: {{ $auth0TokenURL | b64enc }}
  PLATFORM_ORG_SERVICE_ENDPOINT.secret: {{ $platformOrgURL | b64enc }}
  SLACK_WEBHOOK_URL.secret: {{ $slackWebhookURL | b64enc }}
kind: Secret
metadata:
  namespace: '{{ .Values.namespace }}'
  name: {{ .Values.apiSecret }}
  labels:
    type: 'secret'
    app.kubernetes.io/name: {{ include "da-affiliation.name" . }}
    helm.sh/chart: {{ include "da-affiliation.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: {{ .Values.secretType }}
{{ end }}
