{{- $skipSecrets := .Values.skipSecrets -}}
{{ if not $skipSecrets }}
{{- $apiDBEndpoint := .Files.Get (printf "secrets/API_DB_ENDPOINT.%s.secret" .Values.deployEnv) -}}
{{- $shDBEndpoint := .Files.Get (printf "secrets/SH_DB_ENDPOINT.%s.secret" .Values.deployEnv) -}}
{{- $esURL := .Files.Get (printf "secrets/ELASTIC_URL.%s.secret" .Values.deployEnv) -}}
{{- $esUser := .Files.Get (printf "secrets/ELASTIC_USERNAME.%s.secret" .Values.deployEnv) -}}
{{- $esPass := .Files.Get (printf "secrets/ELASTIC_PASSWORD.%s.secret" .Values.deployEnv) -}}
{{- $auth0Cid := .Files.Get (printf "secrets/AUTH0_CLIENT_ID.%s.secret" .Values.deployEnv) -}}
{{- $auth0Dom := .Files.Get (printf "secrets/AUTH0_DOMAIN.%s.secret" .Values.deployEnv) -}}
{{- $auth0Ucl := .Files.Get (printf "secrets/AUTH0_USERNAME_CLAIM.%s.secret" .Values.deployEnv) -}}
{{- $cors := .Files.Get (printf "secrets/CORS_ALLOWED_ORIGINS.%s.secret" .Values.deployEnv) -}}
---
apiVersion: v1
data:
  API_DB_ENDPOINT.secret: {{ $apiDBEndpoint | b64enc }}
  SH_DB_ENDPOINT.secret: {{ $shDBEndpoint | b64enc }}
  ELASTIC_URL.secret: {{ $esURL | b64enc }}
  ELASTIC_USERNAME.secret: {{ $esUser | b64enc }}
  ELASTIC_PASSWORD.secret: {{ $esPass | b64enc }}
  AUTH0_CLIENT_ID.secret: {{ $auth0Cid | b64enc }}
  AUTH0_DOMAIN.secret: {{ $auth0Dom | b64enc }}
  AUTH0_USERNAME_CLAIM.secret: {{ $auth0Ucl | b64enc }}
  CORS_ALLOWED_ORIGINS.secret: {{ $cors | b64enc }}
kind: Secret
metadata:
  namespace: '{{ .Values.namespace }}'
  name: {{ .Values.apiSecret }}
  labels:
    type: 'secret'
    app.kubernetes.io/name: {{ include "da-affiliation.name" . }}
    helm.sh/chart: {{ include "da-affiliation.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: {{ .Values.secretType }}
{{ end }}
